version: 2.1

orbs:
  android: wordpress-mobile/android@0.0.23
  slack: circleci/slack@2.5.0

commands:
  copy-gradle-properties:
    steps:
      - run:
          name: Setup gradle.properties
          command: cp gradle.properties-example gradle.properties

jobs:
  Lint:
    executor: 
      name: android/default
      api-version: "29"
    steps:
      - checkout
      - android/restore-gradle-cache
      - copy-gradle-properties
      - run:
          name: Check Style
          command: ./gradlew --stacktrace checkstyle ktlint
      - run:
          name: Lint
          command: |
            ./gradlew --stacktrace lintRelease || (grep -A20 -B2 'severity="Error"' */build/**/*.xml; exit 1);
      - android/save-gradle-cache
      - android/save-lint-results
  Unit Tests:
    executor: 
      name: android/default
      api-version: "29"
    steps:
      - checkout
      - android/restore-gradle-cache
      - copy-gradle-properties
      - run:
          name: Unit tests
          command: ./gradlew --stacktrace -PtestsMaxHeapSize=1536m testRelease
      - android/save-gradle-cache
      - android/save-test-results

workflows:
  portkey:
    jobs:
      - Lint
      - Unit Tests
